config/routes.rb
Rails.application.routes.draw do

  
  
  get '/manager-admin/login'  => 'admin#login'
  post '/manager-admin/login'  => 'admin#login'
  get '/manager-admin/logout'  => 'admin#logout'
  
  resources :reviews, path: '/manager-admin/reviews'
  resources :categories, path: '/manager-admin/categories'
  resources :users, path: '/manager-admin/users'
  resources :sub_categories, path: '/manager-admin/sub-categories'
  resources :sites, path: '/manager-admin/sites'
  resources :images, path: '/manager-admin/images'
  
  root 'front#index'
  get 'feed' => 'front#feed'
  get "sitemap" => "front#sitemap", format: :xml, as: :sitemap
  get '/category/:categorySlug'  => 'front#categories'
  
  get '/review/search'  => 'front#search'
  get '/:categorySlug/:subCategorySlug' => 'front#subCategories'
  
  
  get '/:reviewSlug'  => 'front#reviewDetails'
  get '/go/offer/:id'  => 'front#go'
  
  
  

  

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :checkadmin
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:category_id, :title, :description, :total_viewed, :image, :slug)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :total_viewed %><br>
    <%= f.number_field :total_viewed %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th>Total viewed</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.category %></td>
        <td><%= sub_category.title %></td>
        <td><%= sub_category.description %></td>
        <td><%= sub_category.total_viewed %></td>
        <td><%= sub_category.image %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form' %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @sub_category.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sub_category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sub_category.description %>
</p>

<p>
  <strong>Total viewed:</strong>
  <%= @sub_category.total_viewed %>
</p>

<p>
  <strong>Image:</strong>
  <%= @sub_category.image %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>