config/routes.rb
Rails.application.routes.draw do

  
  
  get '/manager-admin/login'  => 'admin#login'
  post '/manager-admin/login'  => 'admin#login'
  get '/manager-admin/logout'  => 'admin#logout'
  
  resources :reviews, path: '/manager-admin/reviews'
  resources :categories, path: '/manager-admin/categories'
  resources :users, path: '/manager-admin/users'
  resources :sub_categories, path: '/manager-admin/sub-categories'
  resources :sites, path: '/manager-admin/sites'
  resources :images, path: '/manager-admin/images'
  
  root 'front#index'
  get 'feed' => 'front#feed'
  get "sitemap" => "front#sitemap", format: :xml, as: :sitemap
  get '/category/:categorySlug'  => 'front#categories'
  
  get '/review/search'  => 'front#search'
  get '/:categorySlug/:subCategorySlug' => 'front#subCategories'
  
  
  get '/:reviewSlug'  => 'front#reviewDetails'
  get '/go/offer/:id'  => 'front#go'
  
  
  

  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reviewsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="row">
        
        <div class="large-4 large-centered medium-9 columns">
            <%= yield %>
        </div>
    
    </div>
   
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reviewsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="row">
        <div class="large-3 medium-3 columns">
            <div class="panel">
                 <ul class="side-nav" role="navigation" title="Link List">
                   <li role="menuitem"> <%= link_to 'Reviews', reviews_path() %> </li>
                   <li role="menuitem"><%= link_to 'Categories', categories_path() %></li>
                   <li role="menuitem"><%= link_to 'Sub Categories', sub_categories_path() %></li>
                   <li role="menuitem"><%= link_to 'Users', users_path() %></li>
                   <li role="menuitem"><%= link_to 'Images', images_path() %></li>
                   <li role="menuitem"><%= link_to 'Site settings', sites_path() %></li>
                   <li role="menuitem"><%= link_to 'Logout', :controller => "admin", :action => "logout" %></li>
                 </ul>
            </div>
            
        </div>
        
        <div class="large-9 medium-9 columns">
            <%= yield %>
        </div>
        
    
    </div>
   
</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><% if defined?(@subtitle) %> <%= @subtitle %> - <% end %><%= @site.title %></title>
    <link rel="profile" href="http://gmpg.org/xfn/11">
    
    <meta name="description" content="<%=strip_tags @description %>"/>
    <link rel="canonical" href="<%= @site.url %>" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="website" />
    
    <meta property="og:title" content="<%= @site.title %>" />
    <meta property="og:description" content="<%=strip_tags @description %>" />
    <meta property="og:url" content="<%= @url %>" />
    <meta property="og:site_name" content="<%= @site.title %>" />
    <meta property="og:image" content="<%= @site.url %><%= @image %>" />
    
    <% if @home==1 %>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "url": "<%= @site.url %>",
        "name": "<%= @site.title %>",
        "potentialAction":{"@type":"SearchAction","target":"<%= @site.url %>/?s={search_term_string}",
        "query-input":"required name=search_term_string"}
      }
    </script>
    <% end %>
    
    <%= @site.meta_tags.html_safe %>
    
  <link rel="alternate" type="application/rss+xml" title="<%= @site.title %> &raquo; Feed" href="<%= @site.url %>/feed.rss" />
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  
  
  <%= csrf_meta_tags %>
</head>
<body>
        
        <nav class="top-bar" data-topbar role="navigation">
            <div class="large-10 large-centered columns">
              <ul class="title-area large-4">
                <li class="name">
                  <h1><a href="/"><img src="<%= @site.logo %>" id="logo" /></a></h1>
                </li>
                 <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
              </ul>
        
              <section class="top-bar-section large-6">
                <!-- Right Nav Section -->
                <ul class="left">
                  
                  <li class="has-dropdown">
                    <a href="#"><i class="fa fa-th"></i> Categories</a>
                    <ul class="dropdown">
                        <% @headerCategories.each do |hCategory| %>
                          <li><a href="/category/<%= hCategory.slug %>"> <%= hCategory.title %> </a></li>
                        <% end %>
                    </ul>
                  </li>
                  
                  <li class="has-dropdown">
                    <a href="#"><i class="fa fa-location-arrow"></i> Top reviews</a>
                    <ul class="dropdown">
                        <% @headerPopularReviews.each do |hPopReviews| %>
                          <li><a href="/<%= hPopReviews.slug %>"><%= hPopReviews.title %></a></li>
                        <% end %>
                    </ul>
                  </li>
                </ul>
              </section>
            </div>
        </nav>
    
        
            <%= yield %>
        <footer>
            <div class="large-12 footer-top">
                <div class="row">
                    <div class="large-4 columns">
                        <div class="panel">
                            <h4 class="title">Browse top categories</h4>
                            <ul class="side-nav">
                              <% @footerCategories.each do |fCategory| %>
                                  <li><a href="/category/<%= fCategory.slug %>"> <%= fCategory.title %> </a></li>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="large-4 columns">
                        <div class="panel">
                            <h4 class="title">Most Popular Reviews</h4>
                            <ul class="side-nav">
                            <% @footerPopularReviews.each do |fPopReviews| %>
                              <li><a href="/<%= fPopReviews.slug %>"><%= fPopReviews.title %></a></li>
                            <% end %>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="large-4 columns footer-highlight">
                        <div class="panel">
                            <div class="large-12">
                                <h3 class="text-center">
                                    <% if defined?(@site.facebook_url) %> <a href="<%= @site.facebook_url %>" target="_blank"><i class="fa fa-facebook"></i></a><% end %>
                                    <% if defined?(@site.twitter_url) %> <a href="<%= @site.twitter_url %>" target="_blank"><i class="fa fa-twitter"></i></a><% end %>
                                    <% if defined?(@site.gplus_url) %> <a href="<%= @site.gplus_url %>" target="_blank"><i class="fa fa-google-plus"></i></a><% end %>
                                    <% if defined?(@site.youtube_url) %> <a href="<%= @site.youtube_url %>" target="_blank"><i class="fa fa-youtube"></i></a><% end %>
                                </h3>
                            </div>
                            <div class="large-12">
                                <img src="<%= @site.footer_logo %>" />
                            </div>
                            
                            <div class="large-12 text-center">
                                <h5>
                                    Built with <i class="fa fa-heart-o" data-tooltip aria-haspopup="true" class="has-tip" title="Love and Care"></i> 
                                    <i class="fa fa-html5" data-tooltip aria-haspopup="true" class="has-tip" title="HTML5"></i> 
                                    <i class="fa fa-css3" data-tooltip aria-haspopup="true" class="has-tip" title="CSS3"></i>
                                
                                </h5>
                            </div>
                        </div>
                    </div>
                    
                    </div>
                </div>
            </div>
            <div class="large-12 text-center columns footer-bottom">
                Copyright © 2015 99 Reviews. All Rights Reserved.
            </div>
        </div>
    </footer>
   
    <script>
        $(document).foundation({
          equalizer : {
            equalize_on_stack: true
          }
        });
    </script>
</body>
</html>